### ISSUE TITLE
[iOS] object cannot be nil 

### ISSUE THREAD

**Issue by dinhtrumdieu** [gevgasparyan/rn-qr-generator#11]
Hey guys!

I get this error when use this image: https://i.imgur.com/QVcnOb7.png

`ExceptionsManager.js:126 Exception '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil' was thrown while invoking detect on target RNQrGenerator with params (
        {
        uri = "https://i.imgur.com/QVcnOb7.png";
    },
    3580,
    3581
)
callstack: (
	0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049d77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff2049b656 -[__NSArrayM insertObject:atIndex:].cold.2 + 0
	4   CoreFoundation                      0x00007fff2031e678 -[__NSArrayM insertObject:atIndex:] + 1134
	5   CarOCRApp                           0x000000010ff263c1 __56-[RNQrGenerator detect:failureCallback:successCallback:]_block_invoke + 145
	6   CoreFoundation                      0x00007fff2039239f __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	7   CoreFoundation                      0x00007fff2031ea34 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 224
	8   CarOCRApp                           0x000000010ff25fa0 -[RNQrGenerator detect:failureCallback:successCallback:] + 1728
	9   CoreFoundation                      0x00007fff204272fc __invoking___ + 140
	10  CoreFoundation                      0x00007fff204247b6 -[NSInvocation invoke] + 303
	11  CoreFoundation                      0x00007fff20424a47 -[NSInvocation invokeWithTarget:] + 70
	12  CarOCRApp                           0x000000011004d3b4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660
	13  CarOCRApp                           0x000000011005155e _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 814
	14  CarOCRApp                           0x0000000110051026 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 134
	15  CarOCRApp                           0x0000000110050f8c ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	16  libdispatch.dylib                   0x00000001115c47ec _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00000001115c59c8 _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00000001115d3e75 _dispatch_main_queue_callback_4CF + 1152
	19  CoreFoundation                      0x00007fff2038edbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	20  CoreFoundation                      0x00007fff2038963e __CFRunLoopRun + 2685
	21  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567
	22  GraphicsServices                    0x00007fff2bededb3 GSEventRunModal + 139
	23  UIKitCore                           0x00007fff24690e0b -[UIApplication _run] + 912
	24  UIKitCore                           0x00007fff24695cbc UIApplicationMain + 101
	25  CarOCRApp                           0x000000010fe520c0 main + 112
	26  libdyld.dylib                       0x00007fff202593e9 start + 1
)`

**Additional Info**: I think can't read :' ┐�c�J后山三三質撒撒燦惨'

**Comment by gevgasparyan** [comment]
Hi @dinhtrumdieu.

Can you please add a code snippet as well?

Thanks.

**Comment by dinhtrumdieu** [comment]
My code

**Comment by gevgasparyan** [comment]
Currently detecting remote images is not supported. You can try to download the image using rn-fetch-blob and then pass the downloaded image path to rn-qr-generator.

**Comment by dinhtrumdieu** [comment]
> Currently detecting remote images is not supported. You can try to download the image using rn-fetch-blob and then pass the downloaded image path to rn-qr-generator.
