### ISSUE TITLE
Could not find module RNQRGenerato

### ISSUE THREAD

**Issue by marchetb** [gevgasparyan/rn-qr-generator#12]
Hello,

I got an issue that I dont find a way to resolve.
Juste tried this module on my expo app and can't make it work.

I've done : 
`$ npm install rn-qr-generator --save`
and 
`cd ios && pod install && cd ../`

But when my app is launch on the iOS simulator, I got this error :
**Could not find module "RNQrGenerator".
Did you forget to run "pod install" ?
at node_modules/rn-qr-generator/index.js:6:8 in <global>
at http://127.0.0.1:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:478471:57 in <unknown>
at App.js:28:0 in <global>
at index.js:3:0 in <global>
at http://127.0.0.1:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:479139:3 in global code**

Any help ?
Thanks

**Comment by gevgasparyan** [comment]
Hello @marchetb .

Currently there is no support for the expo projects.

Thanks

**Comment by gevgasparyan** [comment]
@marchetb can you try

`expo install react-native-view-shot`
instead of 
`npm install rn-qr-generator --save` ?

**Comment by LucasWilliams2622** [comment]
> Hello @marchetb .
> 
> Currently there is no support for the expo projects.
> 
> Thanks

Hi @gevgasparyan,

Is there support for expo yet?

Thanks
