### ISSUE TITLE
Detect not working on Android

### ISSUE THREAD

**Issue by jleach** [gevgasparyan/rn-qr-generator#15]
Opening an QR code in iOS works fine but for Android less so; it's not able to find the QR code in the image. I've attached it for testing. This image is fake data and does not represent a real person. The image below comes in as base64 encoded which I pass into detect; Like I said above, iOS nails it 100% of the time so I believe my RN code to be valid.

![image001](https://user-images.githubusercontent.com/390891/137172340-ad5e9f1a-5fb8-4f98-9cc1-e664d738488f.png)

**Comment by gevgasparyan** [comment]
Hi @jleach .
Currently android cannot detect large QR codes
