### ISSUE TITLE
How to generate QR CODE with Arabic characters ?

### ISSUE THREAD

**Issue by abdulrehmankfueit** [gevgasparyan/rn-qr-generator#16]

**Comment by gevgasparyan** [comment]
Hi @abdulrehmankfueit 
I tested it with Arabic characters and it works fine. You can see recorded example


https://user-images.githubusercontent.com/13519034/138046016-e56cbe3b-2122-4bf3-969d-2d65ad0aa06e.mov

Can you please provide an example? So I can test it

**Comment by mghonem** [comment]
> 
> 
> Hi @abdulrehmankfueit I tested it with Arabic characters and it works fine. You can see recorded example
> Screen.Recording.2021-10-20.at.11.17.40.mov
> 
> Can you please provide an example? So I can test it

same issue in Android
