### ISSUE TITLE
Detect not working on Android [QR on slip]

### ISSUE THREAD

**Issue by kittipat3699** [gevgasparyan/rn-qr-generator#23]
**Hello!**

I am trying to use qrcode detect.
It works fine on ios, but I get nothing on android, like this.

`{"type": "", "values": []}`

Could you help me?
Here's the code:

```
const openImageFromGallery = async () => {
    try {
      setIsCloseCamera(true)

      const image = await ImagePicker.openPicker({
        width: width,
        height: height,
        mediaType: 'photo',
      })

      const base64ImgId = await RNFS.readFile(image.path, 'base64')
      const response = await RNQRGenerator.detect({
        uri: image.path,
        base64: base64ImgId,
      })

      if (!_.isEmpty(response.values)) {
        setCode([{ displayValue: response.values[0] }])
      } else {
        setIsCloseCamera(false)
        setIsShowPopupQrInvalid(!isShowPopupQrInvalid)
      }
    } catch (error) {
      console.error('🚀 ~ openImageFromGallery ~ error', error)
      return
    }
  }
```

_this QR code I scan_

![Screen Shot 2565-10-11 at 17 04 35](https://user-images.githubusercontent.com/26093117/195062428-93478b14-6cf0-4108-bbc0-874c2b6c51b0.png)

**Comment by gevgasparyan** [comment]
Hi @kittipat3699. What es device model and OS version?

**Comment by Madubhashana** [comment]
Same. It works fine on iOS. But does not work on android (for these kinds of photographed images only). 
I am using a Samsung A80 device with Android 11
@gevgasparyan

**Comment by janith-rhino** [comment]
**bump**

**Comment by xiaobc1234** [comment]
Is there any other library that can replace

**Comment by xiaobc1234** [comment]
> 

The barcode in the photo cannot be recognized

**Comment by gevgasparyan** [comment]
Hi @kittipat3699 
This module uses `zxing` lib on android.

If you try to decode the image with [zxing online decoder](https://zxing.org/w/decode) it will also be empty. Seems the issue is with decoder.

Will let you know when I find another solution for that.

Thanks

**Comment by rizbud** [comment]
Facing the same issue.
Anyone have found a solution for this?
