### ISSUE TITLE
problems with ZXingObjC in ios

### ISSUE THREAD

**Issue by ombogdanJoinToIt** [gevgasparyan/rn-qr-generator#24]
/ios/Pods/ZXingObjC/ZXingObjC/core/ZXRGBLuminanceSource.m:62:40: error build: No visible @interface for 'ZXByteArray' declares the selector 'initWithArray:length:'

<img width="313" alt="image" src="https://user-images.githubusercontent.com/109798616/195764467-9f8ba7df-3e4f-4504-95cb-987ab855dc5b.png">

**Comment by gevgasparyan** [comment]
what is your cocoapods version? (`pod --version`)

**Comment by eduardobda** [comment]
Same issue here,

Im using pod version 1.11.3
React native 0.69.4
node version 16.17.0

Any way to solve it

**Comment by gevgasparyan** [comment]
The issue was resolved in 1.3.1.
Don't forget to call `pod install`

**Comment by ardiankristo** [comment]
I also found this issue while running in Xcode, solved by downgrading to version `"1.1.4"`

Following the version from this [example](https://github.com/gevgasparyan/rn-qr-generator/blob/master/example/QRGeneratorExample/ios/Podfile.lock#L301) that doesn't have `ZXingObjC` in its PodFile dependency.
