### ISSUE TITLE
Wrong characters in QR code generation

### ISSUE THREAD

**Issue by HugoDuret** [gevgasparyan/rn-qr-generator#27]
Hi guys,

First, thanks for the work done on this library, it is pretty straightforward and reliable.

Then, I ran in a very strange behavior today. I create an app where I need to generate a QR code with some data in it at some point, and scan it later to retrieve the data. The text, of course, must (and should) be the same at the creation and at the scan.

In the text, I separate data with special characters: § and µ
The problem is that these two characters are somehow replaced by the characters ｧ and ｵ between creation and scan, but **only with a short text**. When the text is longer,  § and µ are correctly retrieved.  I can't find an explanation.

To reproduce:

## First (short)
Original string : _1§Name§0µ10_
Resulting QR code: 
![image](https://user-images.githubusercontent.com/44072355/216816767-d83eb31d-9286-473b-abc4-c64010064294.png)

Resulting QR code scanned text : _1ｧNameｧ0ｵ10_

## Second (long)
Original string : _1§Name§0µ10|11|12|13|14|15|16|17|18|19|110|111|112|113_
Resulting QR code: 
![image](https://user-images.githubusercontent.com/44072355/216816848-4bd842e6-3b5d-46d2-a552-57398f0f8c58.png)

Resulting QR code scanned text : _1§Name§0µ10|11|12|13|14|15|16|17|18|19|110|111|112|113_

I generate the QR code in base64 with the following code:
```
const QRCodeImageSize = Dimensions.get('window').height * 0.4;
    RNQRGenerator.generate({
      value: QRCodeData, // as mentioned above
      height: QRCodeImageSize * 5,
      width: QRCodeImageSize * 5,
      base64: true,
      backgroundColor: Styles.COLORS.THEME_WHITE_DARKER,
      padding: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
      },
      correctionLevel: 'L',
    })
``` 

Any help will be appreciated.

**Comment by gevgasparyan** [comment]
Hi @HugoDuret . Could you try the 1.3.1 version?
Thanks
