### ISSUE TITLE
PhonePe QR  detect is not working 

### ISSUE THREAD

**Issue by YB-MDS-sunil-ext** [gevgasparyan/rn-qr-generator#30]
PhonePe QR detection is not working. Getting empty response

const ScanQrCodeFromGallery = () => {
        ImagePicker.openPicker({
            width: 150,
            height: 150,
            cropping: false,
            includeBase64: true,
        })
            .then(async (images) => {
                const imagePath = images?.path;
                const base64ImgId = await RNFS.readFile(imagePath, 'base64')
                RNQRGenerator.detect({
                    base64: base64ImgId
                })
                    .then(response => {
                        const { values } = response;
                        onSuccess(values?.[0]);
                        let galleryImage=true
                        setisQrFromGallery(galleryImage)
                    })
                    .catch(error => {
                        console.log("Your Scan QR is Invalid.")
                    });
            })
            .catch((error) => {
                if ( JSON.stringify(error).includes('User cancelled image selection')){
                    return;
                }
                else {
                  console.log("Your Scan QR is Invalid.")
                }
            })
    }

**Comment by gevgasparyan** [comment]
Hi @YB-MDS-sunil-ext 
please share the base64 string as well.
