### ISSUE TITLE
Detection is not working on Android

### ISSUE THREAD

**Issue by mastro993** [gevgasparyan/rn-qr-generator#31]
We are trying to detect multiple QRCodes from a single image. On iOS everything works fine, but on Android it returns an empty array of values.

An example image we are trying to use is the following: https://github.com/gevgasparyan/rn-qr-generator/assets/6160324/9b6f506e-c636-4c6b-8668-b9f1ea9dd9f0

The online ZXing decoder works fine: https://zxing.org/w/decode?u=https%3A%2F%2Fgithub.com%2Fgevgasparyan%2Frn-qr-generator%2Fassets%2F6160324%2F9b6f506e-c636-4c6b-8668-b9f1ea9dd9f0

This issue does not appear to be related to device type or Android version, we see it on multiple Android devices.

**Comment by gevgasparyan** [comment]
Hey @mastro993

Please try a new 1.4.0 version. Added support for multiple QR code detection.
Don't forget to reinstall the app after updating the library.

**Comment by mastro993** [comment]
Tried with the 1.4.0 version and it works great! Thank you

**Comment by Yunaum** [comment]
> Hey [@mastro993](https://github.com/mastro993)
> 
> Please try a new 1.4.0 version. Added support for multiple QR code detection. Don't forget to reinstall the app after updating the library.

still not working on Android, but works on IOS well, please help me!!
now 1.4.4 version;
1. android/settings.gradle:
`include ':rn-qr-generator'
project(':rn-qr-generator').projectDir = new File(rootDir,'../node_modules/rn-qr-generator/android')
project(':rn-qr-generator').projectDir = new File(rootProject.projectDir,'../node_modules/rn-qr-generator/android')`
2. android/app/build.gradle
`implementation project(':rn-qr-generator') 
implementation 'com.journeyapps:zxing-android-embedded:4.3.0'`
3. android/app/src/main/java/[...]/MainActivity.java
there is no getPackages() method
`import com.gevorg.reactlibrary.RNQrGeneratorPackage;`
4. scan method
` const scanImageForQrCodes = async imageUri => {
    try {
      console.log('start scan:', imageUri);
      
      let finalUri = imageUri;
      if (Platform.OS === 'android') {
        if (imageUri.startsWith('file://')) {
          finalUri = imageUri.replace('file://', '');
        }

        if (imageUri.startsWith('content://')) {
          console.log('for content URI:', imageUri);
        }
      }
  
      console.log('final url:', finalUri);
  
      const fileExists = await RNFS.exists(finalUri);
      console.log('file exists:', fileExists);
  
      if (!fileExists) {
        console.log('file does not exist, can not scan');
        return;
      }
  
      const fileInfo = await RNFS.stat(finalUri);
      console.log('fileInfo:', fileInfo);
  
      const detectionResult = await RNQRGenerator.detect({
        // uri: finalUri,
        base64: await RNFS.readFile(finalUri, 'base64'),
      });
      
      console.log('full check result:', JSON.stringify(detectionResult, null, 2));
      
      const {type, values} = detectionResult;
      if (values && values.length > 0) {
        console.log('✅ has qrcode content:', values);
      } else {
        console.log('❌ no qrcode content');
      }
      
    } catch (err) {
      console.log('scan error:', err);
    }
  };`

still not working on Android, but works on IOS well, please help me!!
