### ISSUE TITLE
RNQRGenerator.detect not working in iOS after updating react-native version from 0.68 to 0.74.1

### ISSUE THREAD

**Issue by Oza-Kaushal** [gevgasparyan/rn-qr-generator#47]
Hi, 

I am using the snipped as below for detect QR image camera using uri.

It was working properly until I upgrade my project from RN 0.68 to 0.74.1

  RNQRGenerator.detect({
              uri: path,
            })
              .then(response => {
                const {values, type} = response;
                let data = "";
                if (Array.isArray(values) && values.length > 0) {
                  data = values[0];
                  this.setState({scan: true});
                  let scanResult = {
                    type: type,
                    data: data,
                  };
                } else {
                  alert(
                    "Image does not seems to be valid QR/Bar Code. Please choose another image to get accurate scan result.",
                  );
                }
              })
              .catch(error => {
                console.log("Cannot detect QR code in image", error);
              });
              
In my above code I am getting empty response as below:
{
    "errorCode": "others"
}

While it is working for the same image in Android.

Please help me on this.

Many thanks in advance.

**Comment by amarstb** [comment]
Hey @Oza-Kaushal were you able to find a fix or any alternate solution?

**Comment by camboYY** [comment]
i face the same, issue.

**Comment by Oza-Kaushal** [comment]
Hello @  @amarstb and @camboYY, 

I found that the issue only occurs on simulator, I tried with real device and it worked.

my current version specs are as below:

"react": "^18.3.1",
"react-native": "0.75.4",
"rn-qr-generator": "^1.4.0",

npm -v --> 10.5.1
node -v  --> v20.11.1

Xcode version 16.0

Android Studio Koala | 2024.1.1 || Build #AI-241.15989.150.2411.11948838, built on June 11, 2024

macOS 15.0.1

java -version -->
openjdk version "17.0.10" 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-17.0.10.7.1 (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.10.7.1 (build 17.0.10+7-LTS, mixed mode, sharing)
