### ISSUE TITLE
how to show QRCode in image

### ISSUE THREAD

**Issue by zainbinfurqan** [gevgasparyan/rn-qr-generator#5]
i am getting this in uri response file:///data/data/com.qrcode/cache/ad58bfa6-994b-48df-9b9a-c6b79d3ef498.png
how can i show with this uri in image i did {{uri:file:///data/data/com.qrcode/cache/ad58bfa6-994b-48df-9b9a-c6b79d3ef498.png}}
but nothing happend

**Comment by gevgasparyan** [comment]
@zainbinfurqan Hey, what is your device model and OS version?

**Comment by gevgasparyan** [comment]
It works fine on iOS 13 but may fail on iOS 14 due to this [issue](https://github.com/facebook/react-native/issues/29279)

Can you confirm that other local images are rendering properly?
