### ISSUE TITLE
Gradient QR code not detect 

### ISSUE THREAD

**Issue by ahsanparacha02** [gevgasparyan/rn-qr-generator#52]
Previously I have used white background to detect QR code but when we have change gradient then it wont detect QR code data. Below mention QR wont detect

Is there any other solution to detect gradient color QR code?

![WhatsApp_Image_2024-10-04_at_4 34 00_PM 1](https://github.com/user-attachments/assets/1d6dd474-16c8-4bda-aeb9-1974da843130)

**Comment by gevgasparyan** [comment]
Hi @ahsanparacha02 
On which platform did you try? iOS or Android

**Comment by ahsanparacha02** [comment]
I have try on both platform getting same issue

**Comment by gevgasparyan** [comment]
Just tried it on iOS and it detected successfully. Using 1.3.1 version
<img width="336" alt="Screenshot 2024-10-10 at 16 59 56" src="https://github.com/user-attachments/assets/2ad9d35a-c7ec-4a34-b3cf-5f21e26d331b">

**Comment by ahsanparacha02** [comment]
Ok i will check with uri can u try on android

**Comment by ahsanparacha02** [comment]
@gevgasparyan any update?

**Comment by gevgasparyan** [comment]
@ahsanparacha02 you can use a new version v1.4.1, seems it can detect QR codes with a gradient background

**Comment by ahsanparacha02** [comment]
> @ahsanparacha02 you can use a new version v1.4.1, seems it can detect QR codes with a gradient background

It’s working fine now, but black and white mode isn’t functioning as it did in version 1.4.0

![WhatsApp Image 2024-10-16 at 12 45 07 PM (3)](https://github.com/user-attachments/assets/6c1b4d52-da92-4856-86a8-1b938f8f00db)

**Comment by gevgasparyan** [comment]
@ahsanparacha02 missed that, try 1.4.2,

**Comment by ahsanparacha02** [comment]
> @ahsanparacha02 missed that, try 1.4.2,

Working fine, thanks @gevgasparyan
