### ISSUE TITLE
We upload some QR and the detect method is not correctly returning response, which mean type = UPE

### ISSUE THREAD

**Issue by camboYY** [gevgasparyan/rn-qr-generator#53]
the fix is here.
ZXDecodeHints *hints = [ZXDecodeHints hints];
[hints addPossibleFormat:kBarcodeFormatQRCode];
ZXResult *result = [reader decode:bitmap hints:hints error:&error];

**Comment by gevgasparyan** [comment]
@camboYY added to 1.4.3 version, thanks
