### ISSUE TITLE
[TypeError: null is not an object (evaluating 'RNQrGenerator.detect')]

### ISSUE THREAD

**Issue by justinhoo888** [gevgasparyan/rn-qr-generator#8]
Hi all,

I hit this error [TypeError: null is not an object (evaluating 'RNQrGenerator.detect')], any idea?

**Comment by varszakaryan** [comment]
Hey, what version of the package and operation system did you use?

**Comment by gevgasparyan** [comment]
Hey @justinhoo888

I guess something is wrong with the linking of the module.

Please uninstall the package and install the latest one (v 1.1.4) and make sure to run `npx jetify` for `Android` and ` cd ios && pod install` for `iOS` and then reinstall the app.

Hope this will help you.
