### ISSUE TITLE
Got "IMAGE_NOT_FOUND"  in   RNQRGenerator.detect

### ISSUE THREAD

**Issue by 58160703** [gevgasparyan/rn-qr-generator#9]
Hi . When I'm trying the example  

`const onPick = () => {
    launchImageLibrary(options, (response) => {
      setDetectImageUri({uri: response.uri});
      RNQRGenerator.detect({uri: response.uri})
        .then((res) => {
          if (res.values.length === 0) {
            setDetectedValues(['QR code not found']);
          } else {
            setDetectedValues(res.values);
          }
        })
        .catch((err) => {
          console.log('Cannot detect', err);
        });
    });
  };
`

the URI from launchImageLibrary is : 

`"content://com.easysandbox.imagepickerprovider/cacheDir/rn_image_picker_lib_temp_10ae8dce-7af8-4bca-b4f4-e7f50ece1157.jpg"`

but when it   RNQRGenerator.detect I got error like 

`Possible Unhandled Promise Rejection (id: 1):
"IMAGE_NOT_FOUND"
`

Do you have any suggestions for my issue?

I'm using 
react-native: 0.60.6 
version of android is :10

Anyways thank you for creating such a good library it's easy to use and makes everything easier.

**Comment by gevgasparyan** [comment]
Hey @58160703 ,

Thanks for reporting.

Sometimes android cannot detect QR code when there is no padding. Can you please attach the image you picked so I will try to find the issue?

Thanks!

**Comment by gevgasparyan** [comment]
Hi @58160703,

Thanks for reporting.
Is it possible to pass base64 instead of path with content scheme?

Currently there is no support for URIs with `content://` scheme.
But it will added soon!

Thanks!

**Comment by 58160703** [comment]
yes, now I'm using the base64 instead, and it's works perfectly!
thank you for your support.
